src/models/TopPosts.py
from datetime import datetime
from src.config import db


class TopPosts(db.Model):
    __tablename__ = "top_posts"
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(200))
    title = db.Column(db.String(200))
    upvotes = db.Column(db.Integer)
    body_text = db.Column(db.String(20000))
    _created_at = db.Column(db.DateTime, default=datetime.utcnow)
    _last_updated_at = db.Column(db.DateTime, default=datetime.utcnow)

src/models/posts.py
from src.extensions import db
from datetime import datetime


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(200))
    title = db.Column(db.String(200))
    upvotes = db.Column(db.Integer)
    body_text = db.Column(db.String(20000))
    _created_at = db.Column(db.DateTime, default=datetime.utcnow)
    _last_updated_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<Post "{self.title}">'

src/__init__.py
from flask import Flask

from config import Config
from src.extensions import db, swagger
from src.extensions import init_reddit_app


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    swagger.init_app(app)
    init_reddit_app(app)
    # reddit_client = init_reddit_client()
    # Register blueprints here
    from src.main import bp as main_bp

    app.register_blueprint(main_bp)

    from src.posts import bp as posts_bp

    app.register_blueprint(posts_bp, url_prefix="/posts")

    from src.reddit import bp as reddit_bp

    app.register_blueprint(reddit_bp, url_prefix="/reddit")

    @app.route("/test/")
    def test_page():
        return "<h1>Testing the Flask Application Factory Pattern</h1>"

    return app

src/blueprints/extract_blueprint.py
from flask import Blueprint
from src.scripts.scrape_reddit import (
    extract_top_posts,
    tranform_posts,
    create_folder_dir,
)
from datetime import datetime
import csv
import json
from src.config import db, reddit_client
from flasgger import swag_from


extract_blueprint = Blueprint("extract_blueprint", __name__)


@extract_blueprint.route("/extract")
@swag_from("specs/extract_post.yml")
def extract_top_post_from_subreddit():
    subreddits = ["nosleep", "amitheasshole"]
    time_filter = "day"

    subreddit_extracts_list = {}
    for subreddit in subreddits:
        scraped_post_df = extract_top_posts(reddit_client, subreddit, 2, time_filter)
        scraped_post_df = tranform_posts(scraped_post_df)
        subreddit_extracts_list[subreddit] = scraped_post_df

    # Get Current Date
    current_date = datetime.utcnow()
    # Write files as csv into a folder for safe keeping
    for subreddit_key, subreddit_extract_df in subreddit_extracts_list.items():
        path = f"./dataset/{current_date.strftime('%Y')}/{current_date.strftime('%m')}/{current_date.strftime('%d')}/{subreddit_key}/{subreddit_key}_{current_date.strftime('%Y-%m-%d')}_extract.csv"
        create_folder_dir(path)
        subreddit_extract_df.to_csv(
            path, encoding="utf-8", sep=",", quoting=csv.QUOTE_NONNUMERIC, index=False
        )
        subreddit_extract_df.to_sql("top_posts", db.engine, if_exists="append")

    return json.dumps({"success": True}), 200, {"ContentType": "application/json"}

src/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from src.main import routes

src/main/routes.py
from src.main import bp
from flask import render_template


@bp.route("/")
def index():
    return render_template("index.html")

src/posts/__init__.py
from flask import Blueprint

bp = Blueprint("posts", __name__)


from src.posts import routes

src/posts/routes.py
from flask import render_template
from src.posts import bp
from src.extensions import db
from src.models.posts import Post


@bp.route("/")
def index():
    posts = Post.query.all()
    return render_template("posts/index.html", posts=posts)


@bp.route("/categories/")
def categories():
    return render_template("posts/categories.html")

src/reddit/__init__.py
from flask import Blueprint

bp = Blueprint("reddit", __name__)


from src.reddit import routes

src/reddit/routes.py
import json
from src.reddit import bp
from src.reddit.scrape_reddit import (
    extract_top_posts,
    tranform_posts,
    create_folder_dir,
)
from datetime import datetime
from flask import current_app
import csv
from src.extensions import db

from src.extensions import reddit_client


@bp.route("/")
def extract_top_post_from_subreddit():
    # return "HELLO"
    subreddits = ["nosleep", "amitheasshole"]
    time_filter = "day"

    subreddit_extracts_list = {}
    print(reddit_client)
    for subreddit in subreddits:
        scraped_post_df = extract_top_posts(
            current_app.reddit_client, subreddit, 2, time_filter
        )
        scraped_post_df = tranform_posts(scraped_post_df)
        subreddit_extracts_list[subreddit] = scraped_post_df

    # Get Current Date
    current_date = datetime.utcnow()
    # Write files as csv into a folder for safe keeping
    for subreddit_key, subreddit_extract_df in subreddit_extracts_list.items():
        path = f"./dataset/{current_date.strftime('%Y')}/{current_date.strftime('%m')}/{current_date.strftime('%d')}/{subreddit_key}/{subreddit_key}_{current_date.strftime('%Y-%m-%d')}_extract.csv"
        create_folder_dir(path)
        subreddit_extract_df.to_csv(
            path, encoding="utf-8", sep=",", quoting=csv.QUOTE_NONNUMERIC, index=False
        )
        subreddit_extract_df.to_sql("posts", db.engine, if_exists="append")

    return json.dumps({"success": True}), 200, {"ContentType": "application/json"}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <style>
        h2 {
            width: 100%;
        }

        .title {
            margin: 5px;
            width: 100%;
        }

        .content {
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }

        .title a {
            color: #00a36f;
            text-decoration: none;
        }

        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }

    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index') }}">FlaskApp</a>
        <a href="{{ url_for('posts.index') }}">Posts</a>
        <a href="{{ url_for('posts.categories') }}">Categories</a>
        <a href="#">Questions</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Home Page of FlaskApp {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the main Flask blueprint</h2>
    </div>
{% endblock %}

src/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Categories {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the categories page within the posts blueprint</h2>
    </div>
{% endblock %}

src/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Posts Page {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the posts Flask blueprint</h2>
        {% for post in posts %}
            <div class="post">
                <p><b>#{{ post.id }}</b></p>
                <p class="title">
                    <b>
                        <a href="#">
                            {{ post.title }}
                        </a>
                    </b>
                </p>
                <div class="content">
                    <p>{{ post.content }}</p>
                </div>
                <hr>
            </div>
        {% endfor %}
    </div>
{% endblock %}